### ISSUE TITLE
Error: "transform-es2015-modules-commonjs" in babel.plugins is not resolved to an absolute path. Please use `require("fable-utils").

### ISSUE THREAD

**Issue by waozixyz** [fable-compiler/static-web-generator#6]
When i try to run this example i get the following error:
```bash
- $ dotnet fable npm-start
Fable (1.2.0-beta-003) daemon started on port 61225
CWD: /home/user/static-page-generator
npm run start

> test@1.0.0 start /home/user/static-page-generator
> fable-splitter -c splitter.config.js -w

[Environment]: development
/home/user/static-page-generator/node_modules/fable-utils/index.js:41
                    throw new Error(
                    ^

Error: "transform-es2015-modules-commonjs" in babel.plugins is not resolved to an absolute path. Please use `require("fable-utils").resolveBabelOptions(babelOptions)` (also when passing the options to other plugins like babel-loader). Check https://goo.gl/dsBqWA for an example.
    at /home/user/static-page-generator/node_modules/fable-utils/index.js:41:27
    at Array.forEach (<anonymous>)
    at validateArray (/home/user/static-page-generator/node_modules/fable-utils/index.js:38:33)
    at Object.exports.validateFableOptions (/home/user/static-page-generator/node_modules/fable-utils/index.js:53:9)
    at fableSplitter (/home/user/static-page-generator/node_modules/fable-splitter/index.js:287:16)
    at Object.<anonymous> (/home/user/static-page-generator/node_modules/fable-splitter/cli.js:99:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 start: `fable-splitter -c splitter.config.js -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-11T12_53_27_150Z-debug.log
Closing Fable daemon...
```

the full error log is:
```bash
- $ cat ~/.npm/_logs/2018-07-11T12_53_27_150Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v9.2.0/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v9.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v9.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle test@1.0.0~prestart: test@1.0.0
6 info lifecycle test@1.0.0~start: test@1.0.0
7 verbose lifecycle test@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle test@1.0.0~start: PATH: /home/user/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/static-page-generator/node_modules/.bin:/home/user/.nvm/versions/node/v9.2.0/bin:/home/user/.local/bin:/home/user/.cabal/bin:/home/user/apps/bin:/home/user/bin:/usr/local/bin:/usr/local/go/bin:/home/user/go/bin:/home/user/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/go/bin
9 verbose lifecycle test@1.0.0~start: CWD: /home/user/static-page-generator
10 silly lifecycle test@1.0.0~start: Args: [ '-c', 'fable-splitter -c splitter.config.js -w' ]
11 silly lifecycle test@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle test@1.0.0~start: Failed to exec start script
13 verbose stack Error: test@1.0.0 start: `fable-splitter -c splitter.config.js -w`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid test@1.0.0
15 verbose cwd /home/user/static-page-generator
16 verbose Linux 4.14.52-1-MANJARO
17 verbose argv "/home/user/.nvm/versions/node/v9.2.0/bin/node" "/home/user/.nvm/versions/node/v9.2.0/bin/npm" "run" "start"
18 verbose node v9.2.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@1.0.0 start: `fable-splitter -c splitter.config.js -w`
22 error Exit status 1
23 error Failed at the test@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by alfonsogarciacaro** [comment]
Hmm, this is quite old. I need to update it. Let me check...

**Comment by MangelMaxime** [comment]
Hello, 
when working with the new docs of Fable.PowerPack. I encounter the same issue, you can find a working version of `splitter.config.js` [here](https://github.com/fable-compiler/fable-powerpack/blob/master/docs/splitter.config.js).

It's using `fableUtils` to resolve the `babelOptions`.

**Comment by waozixyz** [comment]
@MangelMaxime i tried adding the babelOptions and import fableUtils in the spliiter config. however now when i run "dotnet fable npm-start" I just get:

```bash
Fable (1.2.0-beta-003) daemon started on port 61225
CWD: /home/user/static-page-generator
npm run start

> test@1.0.0 start /home/user/static-page-generator
> fable-splitter -c splitter.config.js -w

[Environment]: development
fable: Compilation started at 16:09:50
```

nothing seems to happen after wards, it just says the compilation has started, but nothing else happens
